# POST http://127.0.0.1:5000/data/author/rankgraph
# POST http://127.0.0.1:5000/data/author/rankgraphimage
# POST http://127.0.0.1:5000/data/article/rankgraph
POST http://127.0.0.1:5000/data/article/rankgraphimage
Content-Type: application/json

{
  "data": [
    [
      "a1", ["a", "b", "c"], ["a", "b", "c", "k", "l"], "1993", ["p1", "p2"],"title of a1","nation of p1"
    ],
    [
      "a2", ["c", "d", "e"], ["a", "c", "d", "e", "m", "n"], "1993", ["p1", "p3"],"title of a2","nation of p1"
    ],
    [
      "a3", ["f", "g", "h"], ["c", "d", "f", "g", "h", "o"], "1993", ["p2", "p4", "p5"],"title of a3","nation of p2" 
    ],
    [
      "a4", ["i", "j"], ["c", "d", "p", "q"], "1994", ["p3", "p6"], ["a1", "a2"], "title of a4", "nation of p3"
    ],
    [
      "a5", ["dj", "dk"], ["a", "dj", "dk", "m", "r"], "1994", ["p1", "p7"], ["a1", "a2", "a3"], "title of a5","nation of p1"
    ],
    [
      "a6", ["d", "ac", "ad"], ["d", "ac", "ad", "s", "t"], "1994", ["p8", "p9"], ["a1", "a3"], "title of a6","nation of p8"
    ]
  ],
  "outer-author": "1",
  "author-rank": "20"
}
